### ISSUE TITLE
Any plans for python-3.11 support?

### ISSUE THREAD

**Issue by StyXman** [psd-tools/image-blender#2]
https://gist.github.com/StyXman/24dbc8cdda180a30b14d2da10c698178

I would paste it here, but we're talking about almost 1000 lines of messages.

**Comment by EvgenKo423** [comment]
Sorry for a late reply. I expected to get things tested and fixed on the same day, but this got out of plan.
This module is based on Cython, but releases use a static C code instead for consistency and dependency reasons. To resolve any compatibility issues it should be enough to simply rebuild it with a modern version of Cython.
I've pushed an updated version to PyPI. Thanks for bringing this to my attention!

**Comment by StyXman** [comment]
No pressure, I'm a patient man and I really appreciate your effort. Cheers!
